FROM python:3.11-slim

# Checkout and install dagster libraries needed to run the gRPC server
# exposing your repository to dagster-webserver and dagster-daemon, and to load the DagsterInstance

RUN pip install \
    dagster \
    dagster-postgres \
    dagster-docker \
    dagster-dbt

# Add repository code

WORKDIR /opt/dagster/app

# Run dagster gRPC server on port 4000

EXPOSE 4000
